destination:
    type: wordpress
    host: yourblog
    user: yourname
    pasword: *****
source:
    feed: http://pommetab.com/feed/atom/
hub:
    host: http://localhost:8080
    token: dummy
    callback: http://localhost:3000/callback
    